# Generated by Django 5.2.17 on 2026-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='catalog_default_variant_must_be_active'),
        ),
    ]
