# Generated by Django 5.2.17 on 2026-09-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_catalog_default_variant_must_be_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attributedefinition')),
            ],
            options={
                'ordering': ('definition__position', 'position', 'label'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand'),
        ),
        migrations.CreateModel(
            name='CategoryAttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='catalog.category')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='catalog.attributedefinition')),
            ],
            options={
                'ordering': ('position', 'definition__name'),
            },
        ),
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_memberships', to='catalog.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='catalog.product')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', through='catalog.CollectionProduct', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='catalog.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_option_definitions', to='catalog.attributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_definitions', to='catalog.product')),
            ],
            options={
                'ordering': ('position', 'definition__name'),
            },
        ),
        migrations.CreateModel(
            name='VariantOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_values', to='catalog.productoptiondefinition')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_assignments', to='catalog.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='catalog.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('definition', 'slug'), name='catalog_attribute_value_definition_slug'),
        ),
        migrations.AddConstraint(
            model_name='categoryattributedefinition',
            constraint=models.UniqueConstraint(fields=('category', 'definition'), name='catalog_category_attribute_definition'),
        ),
        migrations.AddConstraint(
            model_name='collectionproduct',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='catalog_collection_product'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'value'), name='catalog_product_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='productoptiondefinition',
            constraint=models.UniqueConstraint(fields=('product', 'definition'), name='catalog_product_option_definition'),
        ),
        migrations.AddConstraint(
            model_name='variantoptionvalue',
            constraint=models.UniqueConstraint(fields=('variant', 'option'), name='catalog_variant_one_value_per_option'),
        ),
    ]
