# Generated by Django 5.2.17 on 2026-09-20

import hashlib
import json

from django.db import migrations
from django.utils.text import slugify


def _text(value):
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _slug(model, base, **filters):
    base = slugify(base, allow_unicode=True)[:120] or "option"
    candidate = base
    suffix = hashlib.sha1(base.encode()).hexdigest()[:8]
    index = 0
    while model.objects.filter(**filters, slug=candidate).exists():
        index += 1
        candidate = f"{base[:130]}-{suffix}-{index}"[:140]
    return candidate


def _definition(AttributeDefinition, name):
    existing = AttributeDefinition.objects.filter(name=name).order_by("id").first()
    if existing is not None:
        return existing

    return AttributeDefinition.objects.create(
        name=name,
        slug=_slug(AttributeDefinition, name),
        is_visible=True,
    )


def _value(AttributeValue, definition, label):
    existing = AttributeValue.objects.filter(definition=definition, label=label).first()
    if existing is not None:
        return existing

    return AttributeValue.objects.create(
        definition=definition,
        label=label,
        slug=_slug(AttributeValue, label, definition=definition),
    )


def migrate_legacy_variant_options(apps, schema_editor):
    AttributeDefinition = apps.get_model("catalog", "AttributeDefinition")
    AttributeValue = apps.get_model("catalog", "AttributeValue")
    CategoryAttributeDefinition = apps.get_model("catalog", "CategoryAttributeDefinition")
    ProductOptionDefinition = apps.get_model("catalog", "ProductOptionDefinition")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    VariantOptionValue = apps.get_model("catalog", "VariantOptionValue")

    for variant in ProductVariant.objects.exclude(options={}).select_related("product"):
        if not isinstance(variant.options, dict):
            continue
        for position, (raw_name, raw_value) in enumerate(variant.options.items()):
            definition = _definition(AttributeDefinition, _text(raw_name))
            value = _value(AttributeValue, definition, _text(raw_value))
            option, _ = ProductOptionDefinition.objects.get_or_create(
                product_id=variant.product_id,
                definition=definition,
                defaults={"position": position},
            )
            for category in variant.product.categories.all():
                CategoryAttributeDefinition.objects.get_or_create(
                    category=category,
                    definition=definition,
                    defaults={"position": position},
                )
            VariantOptionValue.objects.get_or_create(
                variant=variant,
                option=option,
                defaults={"value": value},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_attributedefinition_brand_collection_category_parent_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_variant_options, migrations.RunPython.noop),
    ]
