# Generated by Django 5.2.17 on 2026-09-15 07:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productvariant_catalog_default_variant_must_be_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('TEHRAN', 'Tehran'), ('OUTSIDE_TEHRAN', 'Outside Tehran')], max_length=20, unique=True)),
                ('amount_irr', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=24)),
                ('shipping_region', models.CharField(choices=[('TEHRAN', 'Tehran'), ('OUTSIDE_TEHRAN', 'Outside Tehran')], max_length=20)),
                ('shipping_amount_irr', models.PositiveBigIntegerField()),
                ('subtotal_irr', models.PositiveBigIntegerField()),
                ('total_irr', models.PositiveBigIntegerField()),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('product_name', models.CharField(max_length=180)),
                ('variant_name', models.CharField(blank=True, max_length=140)),
                ('unit_price_irr', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total_irr', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'variant'), name='orders_one_reservation_per_variant')],
            },
        ),
    ]
