# Generated by Django 5.2.17 on 2026-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=24),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=12),
        ),
    ]
